config/routes.rb
Rails.application.routes.draw do

  get 'browse/index'
  get 'playground/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "landing_page#index"

  get 'yelp/search'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :trips do
    resources :actions
    end 


  # resources :trips 
  resources :actions do

  end


  get "/actions/search" => "actions#search", as: "actions_search"

  # get "/trips/:id/actions" => "actions#index", as: "action_index" 


  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # get '/logout', to: 'sessions#destroy', via: [:get, :post]
  get 'auth/failure', to: redirect('/')

  get '/redirect/:trip_id', to: 'calendar#redirect', as: 'redirect'
  get '/callback/', to: 'calendar#callback', as: 'callback'

  post '/trips/:trip_id/actions/:id' => "actions#create", as: 'trip_action_create'
  
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user
	has_many :courses_trips
	has_many :courses, through: :courses_trips

	has_many :actions_trips
	has_many :actions, through: :actions_trips

	#scope :match_location, -> () {}
	#scope :method_name, -> (arugment) { where (" column_searching ILIKE ?", "%#{}%")}
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

    def index

    #Before page loads, run a Yelp seach to populate the database
        url = "https://api.yelp.com/v3/businesses/search"
        @all_locations = ["NYC", "San Francisco", "Austin",
             "Boston",
             "Atlanta",
             "Chicago",
             "London",
             "Los Angeles",
             "Melbourne",
             "Seattle",
             "Sydney",
             "Washington",
             "D.C.",
             "Dallas",
             "Providence",
             "San Diego",
             "Santa Monica",
             "Denver",
             "Singapore",
             "Brisbane",
             "Toronto",
             "Online",
             "Detroit",
             "Houston",
             "Miami",
             "Minneapolis",
             "Orlando",
             "Philadelphia",
             "Phoenix",
             "Portland",
             "Raleigh-Durham",
             "Salt Lake City",
             "Tampa",
             "Asheville",
             "Columbus",
             "Wilmington",
             "Charlotte",
             "New Orleans",
             "San Antonio",
             "Boulder",
             "San Jose",
             "Savannah",
             "Bellevue",
             "Orange County",
             "Silicon Valley",
             "Orange City",
             "Paris",
             "Barcelona",
             "Amsterdam",
             "Vancouver",
             "Berkeley",
             "Oakland",
             "Santa Clara",
             "Berlin",
             "Lehi",
             "Evanston",
             "Cleveland",
             "Cincinnati",
             "Pittsburgh",
             "Irvine",
             "Colorado Springs",
             "Grand Rapids",
             "Bangalore",
             "Kansas City",
             "Free",
             "Madrid",
             "Mexico City",
             "Sao Paulo",
             "Caracas",
             "Santiago",
             "Maracaibo",
             "Louisville",
             "Saint Louis",
             "Chattanooga",
             "Memphis",
             "Nashville",
             "Costa Rica",
             "New Jersey",
             "New Haven",
             "Arlington",
             "Tel Aviv",
             "Belo Horizonte",
             "Lille",
             "Bordeaux",
             "Copenhagen",
             "Lisbon",
             "Nantes",
             "Casablanca",
             "Marseille",
             "Brussels",
             "Montreal",
             "Rio de Janeiro",
             "Shanghai",
             "Chengdu",
             "Tokyo",
             "Bali",
             "Milan",
             "Buenos Aires",
             "Kyoto",
             "Truckee",
             "Playa del Carmen",
             "Valencia",
             "Bogota",
             "Johannesburg",
             "Cape Town",
             "Hong Kong",
             "Porto",
             "Medellin",
             "Guadalajara",
             "Victoria",
             "Halifax",
             "Calgary",
             "Kuala Lumpur"]  

        #If parameter queries are present, will show index of activities
        if params[:location].present?

            #Populate Food
            food_search_parameters = {
            term: ["food", "bar"].sample,
            location: params[:location],
            }

            #Populate Sightseeing
            sight_search_parameters = {
            term: ["sightseeing", "museum"].sample,
            location: params[:location],
            }

            #Populate Activities
            activity_search_parameters = {
            term: ["fun", "casual", "coffee", "sports"].sample,
            location: params[:location],
            }

            foodresponse = HTTP.auth("Bearer #{ENV['YELP_API_KEY']}").get(url, params: food_search_parameters)
            sightresponse = HTTP.auth("Bearer #{ENV['YELP_API_KEY']}").get(url, params: sight_search_parameters)
            actresponse = HTTP.auth("Bearer #{ENV['YELP_API_KEY']}").get(url, params: activity_search_parameters)
            
            @foodyelps = foodresponse.parse['businesses']
            @sightyelps = sightresponse.parse['businesses']
            @actyelps = actresponse.parse['businesses']
            
            # Save each yelp result to the database as an action
            @foodyelps.each do |y|
                if Action.find_by(api_reference: y['id']).present?
                    #Skip
                else
                    # If new, make a new entry

                    # To prevent errors if Yelp has no price data
                    if y['price'].present?
                        yelp_price = y['price'].length
                    else
                        yelp_price = nil
                    end

                    Action.create(
                        price: yelp_price, 
                        title: y['name'], 
                        type: "Food", 
                        description: "No description is available for this item yet", #Placeholder text, because Yelp doesn't provide a description from its API
                        location: params[:location], #saves with same location name string as the search
                        api_reference: y['id'], 
                        api_source: "Yelp",
                        picture: y['image_url'],
                        link: y['url']
                    )
                end

            end

            @sightyelps.each do |y|
                if Action.find_by(api_reference: y['id']).present?
                    #Skip
                else
                    # If new, make a new entry

                    # To prevent errors if Yelp has no price data
                    if y['price'].present?
                        yelp_price = y['price'].length
                    else
                        yelp_price = nil
                    end

                    Action.create(
                        price: yelp_price, 
                        title: y['name'], 
                        type: "Sightseeing", 
                        description: "No description is available for this item yet", #Placeholder text, because Yelp doesn't provide a description from its API
                        location: params[:location], #note that location saves as a hash containing latitude, longitude 
                        api_reference: y['id'], 
                        api_source: "Yelp",
                        picture: y['image_url'],
                        link: y['url']
                    )
                end
            end


            @actyelps.each do |y|
                if Action.find_by(api_reference: y['id']).present?
                    #Skip
                else
                    # If new, make a new entry

                    # To prevent errors if Yelp has no price data
                    if y['price'].present?
                        yelp_price = y['price'].length
                    else
                        yelp_price = nil
                    end

                    Action.create(
                        price: yelp_price, 
                        title: y['name'], 
                        type: "Activity", 
                        description: "No description is available for this item yet", #Placeholder text, because Yelp doesn't provide a description from its API
                        location: params[:location], #note that location saves as a hash containing latitude, longitude 
                        api_reference: y['id'], 
                        api_source: "Yelp",
                        picture: y['image_url'],
                        link: y['url']
                    )


                end
            end

        end        


        #Retrieves samples from ActiveRecord to generate the trip
        str = params[:location] 

        @courses = Course.where(" '#{params[:location]}' = ANY (locations)").sample(3)
        # @courses = Course.all.sample(3)
        @activities = Action.where(location: params[:location]).where(type: "Activity").sample(9)
        @restaurants = Action.where(location: params[:location]).where(type: "Food").sample(9)
        @sightseeings = Action.where(location: params[:location]).where(type: "Sightseeing").sample(9)

        @activities_requests = []
        @sights_requests = []
        @foods_requests = []

        @activities.each do |a|
            @activities_requests << HTTP.auth("Bearer #{ENV['YELP_API_KEY']}").get("https://api.yelp.com/v3/businesses/#{a.api_reference}").parse
        end

        @sightseeings.each do |a|
            @sights_requests << HTTP.auth("Bearer #{ENV['YELP_API_KEY']}").get("https://api.yelp.com/v3/businesses/#{a.api_reference}").parse
        end


        @restaurants.each do |a|
            @foods_requests << HTTP.auth("Bearer #{ENV['YELP_API_KEY']}").get("https://api.yelp.com/v3/businesses/#{a.api_reference}").parse
        end


        @ratings = {
            "activities" => [
                @activities_requests[0]['rating'],
                @activities_requests[1]['rating'],
                @activities_requests[2]['rating'],
                @activities_requests[3]['rating'],
                @activities_requests[4]['rating'],
                @activities_requests[5]['rating'],
                @activities_requests[-3]['rating'],
                @activities_requests[-2]['rating'],
                @activities_requests[-1]['rating']],
            "sights" => [
                @sights_requests[0]['rating'],
                @sights_requests[1]['rating'],
                @sights_requests[2]['rating'],
                @sights_requests[3]['rating'],
                @sights_requests[4]['rating'],
                @sights_requests[5]['rating'],
                @sights_requests[-3]['rating'],
                @sights_requests[-2]['rating'],
                @sights_requests[-1]['rating']],
            "foods" => [
                @foods_requests[0]['rating'],

app/helpers/trips_helper.rb
module TripsHelper

	def float_path(float)
		#if a float ends with '.5', add '_half'
		if float.nil?
			return 0
		elsif float.to_f % 1 == 0.5
			return (float-0.5).to_i.to_s + "_half"
		else
			return float.to_i
		end
	end

	def match_stars(float, size)
		folder_path = "public/yelp_stars/web_and_ios/#{size}/#{size}_#{float_path(float)}"
	end

	def match_stars_at_zoom(float, size, zoom)
		folder_path = "public/yelp_stars/web_and_ios/#{size}/#{size}_#{float_path(float)}@#{zoom}x"
	end

end

app/views/trips/_activities.html.erb
<div class="content-title flex-container">
    <div>
        <h3 id="activities-title" class="d-inline" style="size: 1.5rem; margin-top: 20px">Activities</h3> 
        <button type="button" class="btn btn-default btn-sm d-none">
                <i class="fas fa-edit"></i>
        </button>    
    </div>
</div>

<div class="activities-container d-flex justify-content-center" style="flex-grow">
    <% @activities[x..y].each_with_index do |a, n| %>
        <div class="card" style="width: 18rem; overflow: hidden">
                <%if FastImage.size(a.picture) == nil %>
                    <%= image_tag('/alt.png', :class => "card-img-top", :alt => "Card image cap") %>
                <%else%>
                    <%= image_tag(a.picture, :class => "card-img-top", :alt => "Card image cap") %>
                <%end%>
                <div class="card-body">
                    <h5 class="card-title"><%=a.title%></h5>
                    <div>           
                        <%=link_to "#{@reviews['activities'][x+n]} reviews", a.link %> 
                    </div>
                    
                    <p class="actionid d-none"><%=a.id%></p>
                </div>
        </div>
    <% end %>
</div>

app/views/trips/_restaurants.html.erb
<div class="content-title">
    <h3 class="d-inline" style="size: 1.5rem">Restaurants</h3> 
    <button type="button" class="btn btn-default btn-sm d-none">
            <i class="fas fa-edit"></i>
    </button>
</div>

<div class="activities-container d-flex justify-content-center" style="flex-grow">
    <% @restaurants[x..y].each_with_index do |r, n| %>
        <div class="card" style="width: 18rem; d-inline-block">
                <%if FastImage.size(r.picture) == nil %>
                    <%= image_tag('/alt.png', :class => "card-img-top", :alt => "Card image cap") %>
                <%else%>
                    <%= image_tag(r.picture, :class => "card-img-top", :alt => "Card image cap") %>
                <%end%>
                <div class="card-body">
                    <h5 class="card-title"><%=r.title%></h5>
                    <div>           
                        <%#= image_tag match_stars(@ratings['foods'][x+n], "regular")%> <!-- based on --> <%=link_to "#{@reviews['foods'][x+n]} reviews", r.link %> 
                    </div>
                    <!-- <div class="float-right align-bottom" style="vertical-align: bottom">
                        Powered by <%#= image_tag "yelp_logo/Yelp_trademark_RGB_outline", :style => "width: 80px; margin: 0px" %>
                    </div> -->
                    <p class="actionid d-none"><%=r.id%></p>
               </div>     
        </div>
    <% end %>
</div>

app/views/trips/_sightseeings.html.erb
<div class="content-title">
    <h3 class="d-inline" style="size: 1.5rem">Sightseeings</h3> 
    <button type="button" class="btn btn-default btn-sm d-none">
            <i class="fas fa-edit"></i>
    </button>
</div>



<div class="activities-container d-flex justify-content-center" style="flex-grow">
    <% @sightseeings[x..y].each_with_index do |s, n| %>
        <div class="card" style="width: 18rem; d-inline-block">
                    <button type="button" class="close d-none" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                <%if FastImage.size(s.picture) == nil %>
                    <%= image_tag('/alt.png', :class => "card-img-top", :alt => "Card image cap") %>
                <%else%>
                    <%= image_tag(s.picture, :class => "card-img-top", :alt => "Card image cap") %>
                <%end%>
                <div class="card-body">
                    <h5 class="card-title"><%=s.title%></h5>
                    <div>           
                        <%#= image_tag match_stars(@ratings['sights'][x+n], "regular")%> <!-- based on --> <%=link_to "#{@reviews['sights'][x+n]} reviews", s.link %> 
                    </div>
                   <!--  <div class="float-right align-bottom" style="vertical-align: bottom">
                        Powered by <%#= image_tag "yelp_logo/Yelp_trademark_RGB_outline", :style => "width: 80px; margin: 0px" %>
                    </div> -->
                    <p class="actionid d-none"><%=s.id%></p>
                </div>
        </div>
    <% end %>
</div>

app/views/trips/show.html.erb
<div class="trip-title">
	<h1 class="text-center h2 mb-3 font-weight-light"> Your trip to: <%=@trip.location%></h1>

    <%if @trip.start_date != nil && @trip.end_date != nil%>
	<p class="text-center mb-3 h6 font-italic font-weight-ligh" style="color: #D7E5DE">Starts from: <strong> <%= @trip.start_date.strftime('%a, %d %b %Y')%> </strong> and ends on: <strong> <%= @trip.end_date.strftime('%a, %d %b %Y')%> </strong></p>
	<br/>
    <%end%>

    <div class="trip-content">
        <p> <%= @course.title%> </p>
        <p> <%= @course.course_provider%> </p>
        <p> Estimated to be <%= @course.duration%> days, or <%= @course.duration/7%> weeks</p>
    	<div class="textarea trip-content" ><%= raw @course.description.gsub("\\n", "").gsub("\\", "")%></div>
        <br/>
        <a style="color: white; text-decoration: underline;" href=<%=@course.link%>>Check out more on SwitchUp!</a>
    </div>
</div>

<div class="darken-overlay">
	<img src="https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" id="coding-pic">
</div> <br/><br/>

<div class="content-title flex-container text-center">
    <div>
        <h1 class="text-center h2 mb-3 font-weight-light d-inline">Activities</h1>    
    </div>
</div> <br/>

<div class="activities-container d-flex justify-content-center" style="flex-grow">
    <% @activities.each_with_index do |a, ind| %>
        <div class="card actions">
                <%if FastImage.size(a.picture) == nil %>
                    <%= image_tag('/alt.png', :class => "card-img-top", :alt => "Card image cap") %>
                <%else%>
                    <%= image_tag(a.picture, :class => "card-img-top", :alt => "Card image cap") %>
                <%end%>
                <div class="card-body">
                    <h5 class="card-title"><%=link_to "#{a.title}", a.link%></h5>
                    <p class="card-text"><%=a.description%></p>
                     <div>           
                       <%=link_to "#{@reviews['activities'][ind]} reviews from Yelp", a.link %> 
                    </div>
                    <%=link_to "Delete", trip_action_path(params[:id], a.id), method: :delete, data: { confirm: 'Are you sure you want to delete this action?' }, :class => "btn btn-danger float-right"%>
                </div>
        </div>
    <% end %>
    <div class="card actions">
        <img class="card-img-top" src="http://www.quantumforquants.org/wp-content/themes/qaengine/img/default-thumbnail.jpg" alt="Card image cap" style="">
        <div class="card-body">
            <%= link_to "Add a new action",  "/trips/#{params[:id]}/actions?actiontype=Activity", class: "card-title", style: "font-size: 1.25rem; font-family: Arial, Helvetica, sans-serif"%>
        </div>
        </div>
    </div>
</div><br/>

<div class="content-title flex-container text-center">
    <div>
        <h1 class="text-center h2 mb-3 font-weight-light d-inline">Food</h1>    
    </div>
</div> <br/>

<div class="activities-container d-flex justify-content-center" style="flex-grow">
    <% @foods.each_with_index do |f, ind| %>
        <div class="card actions">
                <%if FastImage.size(f.picture) == nil %>
                    <%= image_tag('/alt.png', :class => "card-img-top", :alt => "Card image cap") %>
                <%else%>
                    <%= image_tag(f.picture, :class => "card-img-top", :alt => "Card image cap") %>
                <%end%>
                <div class="card-body">
                    <h5 class="card-title"><%=link_to "#{f.title}", f.link %></h5>
                    <p class="card-text"><%=f.description%></p>
                     <div>           
                        <%=link_to "#{@reviews['foods'][ind]} reviews from Yelp", f.link %> 
                    </div>
                    <%=link_to "Delete", trip_action_path(params[:id], f.id), method: :delete, data: { confirm: 'Are you sure you want to delete this action?' }, :class => "btn btn-danger float-right"%>
                </div>
        </div>
    <% end %>
    <div class="card actions">
                <img class="card-img-top" src="http://www.quantumforquants.org/wp-content/themes/qaengine/img/default-thumbnail.jpg" alt="Card image cap" style="">
                <div class="card-body">
                    <%= link_to "Add a new action",  "/trips/#{params[:id]}/actions?actiontype=Food", class: "card-title", style: "font-size: 1.25rem; font-family: Arial, Helvetica, sans-serif"%>
                </div>
        </div>
</div><br/>

<div class="content-title flex-container text-center">
    <div>
        <h1 class="text-center h2 mb-3 font-weight-light d-inline">Sightseeings</h1>    
    </div>
</div> <br/>

<div class="activities-container d-flex justify-content-center" style="flex-grow">
    <% @sightseeings.each_with_index do |s, ind| %>
        <div class="card actions">
                <%if FastImage.size(s.picture) == nil %>
                    <%= image_tag('/alt.png', :class => "card-img-top", :alt => "Card image cap") %>
                <%else%>
                    <%= image_tag(s.picture, :class => "card-img-top", :alt => "Card image cap") %>
                <%end%>
                <div class="card-body">
                    <h5 class="card-title"><%=link_to "#{s.title}", s.link%></h5>
                    <p class="card-text"><%=s.description%></p>
                    <div>           
                         <%=link_to "#{@reviews['sights'][ind]} reviews from Yelp", s.link %> 
                    </div>
                    <%=link_to "Delete", trip_action_path(params[:id], s.id), method: :delete, data: { confirm: 'Are you sure you want to delete this action?' }, :class => "btn btn-danger float-right"%>
                </div>
        </div>
    <% end %>
     <div class="card actions">
                <img class="card-img-top" src="http://www.quantumforquants.org/wp-content/themes/qaengine/img/default-thumbnail.jpg" alt="Card image cap" style="">
                <div class="card-body">
                    <%= link_to "Add a new action",  "/trips/#{params[:id]}/actions?actiontype=Sightseeing", class: "card-title", style: "font-size: 1.25rem; font-family: Arial, Helvetica, sans-serif"%>
                </div>
        </div>
</div>

<style>
.navbar {
	position: absolute;
}

.card-img-top {
object-fit: cover; 
width: 286px; 
height: 180px;
}
</style>