config/routes.rb
Rails.application.routes.draw do

  get 'browse/index'
  get 'playground/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "landing_page#index"

  get 'yelp/search'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :trips do
    resources :actions
    end 


  # resources :trips 
  resources :actions do

  end


  get "/actions/search" => "actions#search", as: "actions_search"

  # get "/trips/:id/actions" => "actions#index", as: "action_index" 


  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # get '/logout', to: 'sessions#destroy', via: [:get, :post]
  get 'auth/failure', to: redirect('/')

  get '/redirect/:trip_id', to: 'calendar#redirect', as: 'redirect'
  get '/callback/', to: 'calendar#callback', as: 'callback'

  post '/trips/:trip_id/actions/:id' => "actions#create", as: 'trip_action_create'
  
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

index_name([Rails.env,base_class.to_s.pluralize.underscore].join('_'))

has_many  :trips, dependent: :destroy

has_many :authentications, dependent: :destroy

mount_uploader :avatar, AvatarUploader

 def self.create_with_auth_and_hash(authentication, auth_hash)

    user = nil
    if auth_hash[:provider] == 'facebook'
      x = auth_hash["info"]["name"].split(" ")

       user = self.create!(
         first_name: x.shift, 
         last_name: x.join(" "),
         email: auth_hash["info"]["email"],
        
         password: SecureRandom.hex(10)
       )
         user.remote_avatar_url = auth_hash["info"]["image"]
         user.save
    else 
       user = self.create!(
         first_name: auth_hash["info"]["first_name"],
         last_name: auth_hash["info"]["last_name"],
         
         email: auth_hash["info"]["email"],
         
         password: SecureRandom.hex(10)
       )
       user.remote_avatar_url = auth_hash["info"]["image"]
       user.save
    end
   user.authentications << authentication
   return user

 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end

def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end





end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

before_action :signed_in_user, only: [:edit, :update]
before_action :correct_user, only: [:edit, :update, :destroy]


def new
	@user = User.new
end 


def create

	@user = User.new(user_from_params)
	if @user.save
		sign_in @user
		#logs in user 
		flash[:success] = "Welcome to Pegatrip"
		redirect_to @user
	else 
		render new_user_path
	end 
end 


def index
	@users = User.all
end 


def show
	@user = User.find(params[:id])
	@trips = Trip.where(:user_id => @user.id).order(start_date: :desc)

	
end 


def edit
	@user = User.find(params[:id])
end 


def update

	@user = User.find(params[:id])
	if @user.update(user_from_params)
		
		redirect_to @user
	else 
		render 'edit'
	end 
end 

def destroy
	@user = User.find(params[:id])
	@user.destroy
	flash[:danger] = "User deleted"
	redirect_to root_path

end 


	private 

	def user_from_params 

		params.require(:user).permit(:first_name, :last_name, :email, :password, :interest, :avatar)
#need to add image here? yes
	end 

	def signed_in_user
		unless signed_in? 
		redirect_to sign_in_path
		end 
	end 

	def correct_user
		@user = User.find(params[:id])
		unless @user == current_user
		redirect_to root_path 
		end 
	end 
		#email = user_params.delete(:email)
    	#password = user_params.delete(:password)
    	#first_name = user_params.delete(:first_name)
    	#last_name = user_params.delete(:last_name)

	    #Clearance.configuration.user_model.new(user_params).tap do |user|
	    #  user.email = email
	    #  user.password = password
	    #  user.first_name = first_name
	    #  user.last_name = last_name
end 

app/views/users/_form.html.erb
<div class = "container col-md-10 text-center">
  <div class="text-field">	
    <%= form.label :first_name, :style => "font-size: 18px" %>
    <%= form.text_field :first_name, type: 'form-control', :class => "form-control" %>
  </div>
 <br/>

  <div class="text-field">	
    <%= form.label :last_name, :style => "font-size: 18px" %>
    <%= form.text_field :last_name, type: 'form-control', :class => "form-control" %>
  </div>
 <br/>

  <div class="text-field">
    <%= form.label :email, :style => "font-size: 18px" %>
    <%= form.text_field :email, type: 'email', :class => "form-control" %>
  </div>
 <br/>
  <div class="password-field">
    <%= form.label :password, :style => "font-size: 18px" %>
    <%= form.password_field :password, :class => "form-control" %>
  </div>
 <br/>
  <div class="text-field">
    <%= form.label :interest, :style => "font-size: 18px" %>
    <%= form.text_field :interest, :class => "form-control" %>
  </div>
 <br/>

  <div class= "avatar-field">
  <%= form.label :avatar, :style => "font-size: 18px" %>
  <%= form.file_field :avatar%>
 
  </div>
 <br/>
      <div>
      <%= form.submit :class => "btn btn-outline", :style => "border-color: #3ac9c6; color: #3ac9c6" %>
        </div>

</div>

app/views/users/edit.html.erb
	<h2 class="text-center">Edit Profile </h2>
	<br/>

	<br/>
	 <div class="container d-flex justify-content-between">
   		<div class="d-inline-block" style="width: 60%" >
	<%= form_for @user do |form| %>
		<%= render partial: '/users/form', object: form %>
  	<% end %>


  	 	</div>
	

		<div class="container d-inline-block mx-auto text-center" style="width: 30%; padding-top: 40px">
			<% if @user.avatar.url == nil%>
				<%= image_tag "/default_profile.png", :class => "profile-pic-edit"%>
			<% else %>
			 	<%= image_tag @user.avatar.url, :class => "profile-pic-edit"%> 

			

			<% end %>
		</div>


</div>

app/views/users/new.html.erb
<div class="sign-up">
  <h2>Sign-up</h2>
  <div class= "sign-up-table">
  	<%= form_for @user do |form| %>
	  	<%= render partial: '/users/form', object: form %>
  	<% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mx-auto mt-5">
	<div class= "profile">
		<div class="row">
   			<div class="col-6">
				<div class= "name">
					<h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
				</div>
				<p>Email: <%=@user.email%> </p>
				<% if @user.interest == nil %>
					<p> Interest:<i> You don't have any interests now. Please go to <b>"Edit profile"</b> to add an activity that you would like to include in your random trips. </i></p>
				<% else %>
					<p>Interest: <%=@user.interest%></p>
				<%end%>
   			</div>

   			<div class="col-6 mx-auto">
				<% if @user.avatar.url == nil%>
					<%= image_tag "/default_profile.png", :class => "profile-pic"%>
				<% else %>
				 	<%= image_tag @user.avatar.url, :class => "profile-pic"%> 
				<% end %>
			</div>
 		</div>
	</div>

<br/><br/> <hr> <br/>

	<% if @user.trips == [] %>
		<p> You don't have any trips yet. </p>
	<% else %>
		<div class="timeline mx-auto">
	    	<% @trips.each do |trip| %>
				 <div class="entry">
				    <div class="title">
					    <%if trip.start_date != nil && trip.end_date != nil%>
					      	<h3>Start date: <%=trip.start_date.strftime('%a, %d %b %Y')%> <br/>End date: <%=trip.end_date.strftime('%a, %d %b %Y')%></h3>
					    <%end%>

				      	<%= link_to trip.location, trip_path(trip.id)%><br/>
				      	<%= link_to "Add to my Google Calendar", redirect_path(trip.id)%>
				    </div>
				    <div class="body">
				    	<%if trip.actions.where(type: "Sightseeing").present? %>
				    		<%= image_tag(trip.actions.where(type: "Sightseeing").first.picture, :style => "height: 180px; width: 180px; margin-left: 20px; border-radius: 100%; object-fit: cover") %>
				    	<%else%>
				    		<%= image_tag('/alt.png', :style => "height: 180px; width: 180px; margin-left: 20px; border-radius: 100%; object-fit: cover") %>					
						<%end%>
				    </div>
				 </div> 
				 <hr style="margin-top: 200px">
	        <%end%>
		</div>
	<%end%>
</div>

<script>
	$('.navbar').css('border-bottom', '1px solid rgba(0,0,0,.1)')
</script>